### ISSUE TITLE
Relation names dont work if not declared in upper case

### ISSUE THREAD

**Issue by mattywausb** [cimt-ag/data_vault_pipelinedescription#179]
Relation names are not normalized at all points in the compiler wich leads to a missmatch, when not written in upper case
This must be fixed. 
Relation names should be set to upper case at all places by the compiler

- [x] DVPDC corrected
- [x] Test added to verify case insensitive behavior

**Comment by jvonhein** [comment]
added tests t1011-t1013

**Comment by jvonhein** [comment]
all changes implemented and pushed to origin/feat/jvonhein

**Comment by mattywausb** [comment]
Reviewed: ok
