### ISSUE TITLE
Old reference data in test cases

### ISSUE THREAD

**Issue by mattywausb** [cimt-ag/data_vault_pipelinedescription#218]
There is old reference data provided and must be updates for the following tests:
please verify the result of the current compile again before placing it as reference
61
220
222
282
285
327
527
622
701
702
703
704

**Comment by albincekaj** [comment]
also
51
65
70

**Comment by mattywausb** [comment]
Checked
- [ ] 51
- [ ] 61
- [ ] 65
- [ ] 70
- [ ] 220
- [ ] 222
- [ ] 282
- [ ] 285
- [ ] 327
- [ ] 527
- [ ] 622
- [ ] 701
- [ ] 702
- [ ] 703
- [ ] 704
