### ISSUE TITLE
Compiler does not warn when adressing the same hub by same relation multiple times

### ISSUE THREAD

**Issue by albincekaj** [cimt-ag/data_vault_pipelinedescription#281]
rtjj_1101_aaa_bbb_lnk [TTT] following parent hub common operation list 
     parent_key_1:  HK_RTJJ_1101_AAA >> HK_RTJJ_1101_AAA  [F1_AAA_BK1F]
     parent_key_2:  HK_RTJJ_1101_BBB_TTT >> HK_RTJJ_1101_BBB_TTTTT  [F3XX_BBB_BK1_TTT|F6XX_BBB_BK2F_TTT]
     parent_key_3:  HK_RTJJ_1101_BBB_TTT >> HK_RTJJ_1101_BBB_UUUUU  [F3XX_BBB_BK1_TTT|F6XX_BBB_BK2F_TTT]
     parent_key_4:  HK_RTJJ_1101_BBB_TTT >> HK_RTJJ_1101_BBB_VVVVV  [F3XX_BBB_BK1_TTT|F6XX_BBB_BK2F_TTT]
     key:  LK_RTJJ_1101_AAA_BBB_TTT >> LK_RTJJ_1101_AAA_BBB  [F1_AAA_BK1F|F3XX_BBB_BK1_TTT|F6XX_BBB_BK2F_TTT|F3XX_BBB_BK1_TTT|F6XX_BBB_BK2F_TTT|F3XX_BBB_BK1_TTT|F6XX_BBB_BK2F_TTT]

rtjj_1101_aaa_bbb_lnk [UUU] following parent hub common operation list 
     parent_key_1:  HK_RTJJ_1101_AAA >> HK_RTJJ_1101_AAA  [F1_AAA_BK1F]
     parent_key_2:  HK_RTJJ_1101_BBB_UUU >> HK_RTJJ_1101_BBB_TTTTT  [F4XX_BBB_BK1_UUU|F7XX_BBB_BK2F_UUU]
     parent_key_3:  HK_RTJJ_1101_BBB_UUU >> HK_RTJJ_1101_BBB_UUUUU  [F4XX_BBB_BK1_UUU|F7XX_BBB_BK2F_UUU]
     parent_key_4:  HK_RTJJ_1101_BBB_UUU >> HK_RTJJ_1101_BBB_VVVVV  [F4XX_BBB_BK1_UUU|F7XX_BBB_BK2F_UUU]
     key:  LK_RTJJ_1101_AAA_BBB_UUU >> LK_RTJJ_1101_AAA_BBB  [F1_AAA_BK1F|F4XX_BBB_BK1_UUU|F7XX_BBB_BK2F_UUU|F4XX_BBB_BK1_UUU|F7XX_BBB_BK2F_UUU|F4XX_BBB_BK1_UUU|F7XX_BBB_BK2F_UUU]

rtjj_1101_aaa_bbb_lnk [VVV] following parent hub common operation list 
     parent_key_1:  HK_RTJJ_1101_AAA >> HK_RTJJ_1101_AAA  [F1_AAA_BK1F]
     parent_key_2:  HK_RTJJ_1101_BBB_VVV >> HK_RTJJ_1101_BBB_TTTTT  [F5XX_BBB_BK1_VVV|F8XX_BBB_BK2F_VVV]
     parent_key_3:  HK_RTJJ_1101_BBB_VVV >> HK_RTJJ_1101_BBB_UUUUU  [F5XX_BBB_BK1_VVV|F8XX_BBB_BK2F_VVV]
     parent_key_4:  HK_RTJJ_1101_BBB_VVV >> HK_RTJJ_1101_BBB_VVVVV  [F5XX_BBB_BK1_VVV|F8XX_BBB_BK2F_VVV]
     key:  LK_RTJJ_1101_AAA_BBB_VVV >> LK_RTJJ_1101_AAA_BBB  [F1_AAA_BK1F|F5XX_BBB_BK1_VVV|F8XX_BBB_BK2F_VVV|F5XX_BBB_BK1_VVV|F8XX_BBB_BK2F_VVV|F5XX_BBB_BK1_VVV|F8XX_BBB_BK2F_VVV]

**Comment by mattywausb** [comment]
Fixed and covered via t1105c
